PUSH_IMAGE = "http://src.push.image.beehoo.cn"
PUSH_IMAGE = "http://apitest.beehoo.cn:9000"
PUSH_IMAGE_CDN = "http://push.image.beehoo.cn"

UPLOAD_FOLDER_HUODONG = "./static/media/huodong/"
UPLOAD_FOLDER_SHIPIN = "./static/media/shipin"
UPLOAD_FOLDER_FENGMIAN = "./static/media/fengmian/"
UPLOAD_FOLDER_LOGO = "./static/media/logo/"
UPLOAD_FOLDER_BANNER = "./static/media/banner/"
UPLOAD_FOLDER_GONGGAO = "./static/media/gonggao/"
UPLOAD_FOLDER_PRESENTER = "./static/media/presenter/"